# Generated by Django 5.2.7 on 2025-11-21 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_recurso_enlace_recurso_imagen_portada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursosKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del recurso')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='recursos_kit/', verbose_name='Archivo')),
                ('tipo_archivo', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Documento Word'), ('xls', 'Excel'), ('ppt', 'PowerPoint'), ('image', 'Imagen'), ('video', 'Video'), ('audio', 'Audio')], max_length=10, verbose_name='Tipo de archivo')),
                ('categoria', models.CharField(choices=[('meditacion', 'Meditación'), ('ansiedad', 'Manejo de Ansiedad'), ('sueno', 'Calidad de Sueño'), ('autocompasion', 'Autocompasión'), ('comunicacion', 'Comunicación'), ('planificacion', 'Planificación'), ('ejercicios', 'Ejercicios Prácticos'), ('guias', 'Guías Rápidas')], max_length=20, verbose_name='Categoría')),
                ('tamaño', models.CharField(help_text='Ej: 2.5 MB', max_length=20, verbose_name='Tamaño del archivo')),
                ('icono', models.CharField(default='fas fa-file-pdf', max_length=50, verbose_name='Icono Font Awesome')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Color del botón')),
                ('descargas', models.PositiveIntegerField(default=0, verbose_name='Número de descargas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('solo_usuarios_registrados', models.BooleanField(default=True, verbose_name='Solo para usuarios registrados')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Recurso del Kit',
                'verbose_name_plural': 'Recursos del Kit',
                'db_table': 'recursos_kit',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DescargaRecursoKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de descarga')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.recursoskit', verbose_name='Recurso')),
            ],
            options={
                'verbose_name': 'Descarga de Recurso Kit',
                'verbose_name_plural': 'Descargas de Recursos Kit',
                'db_table': 'descargas_recursos_kit',
                'unique_together': {('usuario', 'recurso')},
            },
        ),
    ]
